# Tensorflow

Eager Execution en TensorFlow

Eager Execution es una característica de TensorFlow que permite la evaluación de operaciones de inmediato, sin necesidad de construir gráficos computacionales previamente. En contraste con el modo "Graph Execution", donde primero se define un grafo de operaciones y luego se ejecuta, en Eager Execution cada operación se ejecuta paso a paso, lo que facilita la depuración y la experimentación interactiva.

# Definicion de Producto tensorial

![tensor_product](ProductoTensorial.png)

In [42]:
import numpy as np

import tensorflow as tf

a=tf.constant(np.array([1,2,3]))

b=tf.constant(np.arange(4,7))

c_escalar=tf.tensordot(a,b,1)

#Cuando axes = 1 , tf.tensordot realiza un producto escalar (o producto interno) de los dos tensores. 

#En este caso, los tensores de entrada se tratan como vectores, independientemente de su forma, 

#y se realiza un producto escalar de estos vectores.

print(c_escalar)

tf.shape(c_escalar)

tf.Tensor(32, shape=(), dtype=int32)


<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [43]:
#Ahora vamos a hacer un producto tensorial normal

c_tensorial=tf.tensordot(a,b,0) #Con axis=0

print(c_tensorial)

#Aqui se evidencia como funciona en realidad un producto tensorial y el


tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


In [44]:
#Suma de tensores

a_add=tf.constant(np.array([10,20,30]))

b_add=tf.constant(np.array([40,50,60]))

print(tf.add(a_add,b_add)) #Tambien puedo restar usando substract

#Tensor unidimensional de 3 elementos


tf.Tensor([50 70 90], shape=(3,), dtype=int32)


In [45]:
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

Tensor

#Un tensor de 3 dimensiones con 3 capas ,3x3x3

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]])>

In [46]:
#Multiplicacion de matrices con tensores , la clasica


Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])

Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

print(tf.multiply(Matrix_one,Matrix_two))

tf.Tensor(
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]], shape=(3, 3), dtype=int32)


In [47]:
# tf.Variable se utiliza para definir tensores que pueden ser modificados durante la ejecución de un programa.

my_variable = tf.Variable([[1, 2, 3], [4, 5, 6]])

# Imprimir el valor actual de la variable
print(my_variable.numpy())

# Modificar el valor de la variable
my_variable.assign([[7, 8, 9], [10, 11, 12]])

# Imprimir el nuevo valor de la variable
print(my_variable.numpy())

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
